# Generated by Django 4.2.2 on 2023-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=60)),
                ('s_email', models.CharField(max_length=100)),
                ('s_gemder', models.CharField(max_length=5)),
                ('s_picture', models.ImageField(upload_to='images/student/')),
                ('s_dob', models.DateTimeField()),
                ('s_address', models.CharField(max_length=60)),
                ('s_city', models.CharField(max_length=60)),
                ('s_state', models.CharField(max_length=60)),
                ('s_pincode', models.IntegerField(max_length=6)),
                ('s_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
