# Generated by Django 4.2.2 on 2023-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='s_pincode',
            field=models.IntegerField(),
        ),
    ]
