# Generated by Django 4.2.2 on 2023-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymsapi', '0002_alter_student_detail_s_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='s_created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='s_dob',
            field=models.DateField(),
        ),
    ]
