# Generated by Django 4.2.2 on 2023-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ymsapi', '0003_alter_student_detail_s_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=60)),
                ('a_email', models.CharField(max_length=100)),
                ('a_gemder', models.CharField(max_length=5)),
                ('a_picture', models.ImageField(upload_to='images/student/')),
                ('a_dob', models.DateField()),
                ('a_address', models.CharField(max_length=60)),
                ('a_city', models.CharField(max_length=60)),
                ('a_state', models.CharField(max_length=60)),
                ('a_pincode', models.IntegerField()),
                ('a_created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=60)),
                ('t_email', models.CharField(max_length=100)),
                ('t_gemder', models.CharField(max_length=5)),
                ('t_picture', models.ImageField(upload_to='images/student/')),
                ('t_dob', models.DateField()),
                ('t_address', models.CharField(max_length=60)),
                ('t_city', models.CharField(max_length=60)),
                ('t_state', models.CharField(max_length=60)),
                ('t_pincode', models.IntegerField()),
                ('t_created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
